# Generated by Django 6.1.1 on 2026-09-17 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('unit_price', models.BigIntegerField(verbose_name='Birlik narxi')),
                ('unit_cost', models.BigIntegerField(verbose_name='Birlik tannarxi')),
                ('line_total', models.BigIntegerField(verbose_name='Qator summasi')),
            ],
            options={
                'verbose_name': 'Sotuv qatori',
                'verbose_name_plural': 'Sotuv qatorlari',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(verbose_name='Klient ID')),
                ('total', models.BigIntegerField(verbose_name='Jami summa')),
                ('cost_total', models.BigIntegerField(verbose_name='Jami tannarx')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], max_length=10, verbose_name="To'lov turi")),
                ('status', models.CharField(choices=[('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='completed', max_length=10, verbose_name='Holati')),
                ('sold_at', models.DateTimeField(db_index=True, verbose_name='Sotilgan vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqti')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='debt.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
            },
        ),
    ]
