<script setup>
import {
  Clock,
  FileSpreadsheet,
  FileText,
  Globe,
  Info,
  KeyRound,
  Lock,
  Pencil,
  Trash2,
  Percent,
  Phone,
  Ruler,
  Tag,
  Trophy,
  TrendingUp,
  Wallet,
  Banknote,
  Barcode,
  Bell,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  CreditCard,
  Download,
  Droplet,
  Flashlight,
  LogOut,
  Minus,
  Package,
  Plus,
  Receipt,
  RefreshCw,
  Scale,
  Search,
  Settings,
  ShoppingCart,
  Store,
  TriangleAlert,
  User,
  X,
  ArrowLeft,
  Image as ImageIcon,
  ScanBarcode,
} from 'lucide-vue-next'

// One lucide icon set everywhere, addressed by a short semantic name so
// call sites say *what* the icon means (cart, warning, scale...) and the
// mapping to a drawing lives in this one place.
defineProps({
  name: { type: String, required: true },
  size: { type: [String, Number], default: 22 },
})

const icons = {
  cart: ShoppingCart,
  ledger: Receipt,
  receipt: Receipt,
  refresh: RefreshCw,
  box: Package,
  chart: ChartColumn,
  gear: Settings,
  camera: Camera,
  close: X,
  warning: TriangleAlert,
  check: Check,
  'arrow-left': ArrowLeft,
  plus: Plus,
  minus: Minus,
  search: Search,
  'log-out': LogOut,
  download: Download,
  flashlight: Flashlight,
  cash: Banknote,
  card: CreditCard,
  scale: Scale,
  drop: Droplet,
  barcode: Barcode,
  bell: Bell,
  'chevron-down': ChevronDown,
  store: Store,
  user: User,
  calendar: Calendar,
  scan: ScanBarcode,
  gallery: ImageIcon,
  info: Info,
  trend: TrendingUp,
  phone: Phone,
  sheet: FileSpreadsheet,
  file: FileText,
  clock: Clock,
  trophy: Trophy,
  tag: Tag,
  percent: Percent,
  lock: Lock,
  key: KeyRound,
  globe: Globe,
  wallet: Wallet,
  ruler: Ruler,
  pencil: Pencil,
  trash: Trash2,
}
</script>

<template>
  <component :is="icons[name]" v-if="icons[name]" :size="size" aria-hidden="true" />
</template>
