# Generated by Django 6.1.1 on 2026-09-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debt', '0001_initial'),
        ('sales', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='debtentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_entries', to=settings.AUTH_USER_MODEL, verbose_name="Kim tomonidan qo'shildi"),
        ),
        migrations.AddField(
            model_name='debtentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='debt.customer', verbose_name='Mijoz'),
        ),
        migrations.AddField(
            model_name='debtentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_entries', to='sales.sale', verbose_name='Sotuv'),
        ),
        migrations.AddField(
            model_name='debtentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_entries', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', '-debt_balance'], name='debt_custom_shop_id_a014d9_idx'),
        ),
        migrations.AddIndex(
            model_name='debtentry',
            index=models.Index(fields=['customer', '-created_at'], name='debt_debten_custome_21f1f4_idx'),
        ),
    ]
