# Generated by Django 6.1.1 on 2026-09-17 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_initial', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Boshlang'ich miqdor")),
                ('qty_remaining', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qolgan miqdor')),
                ('cost_price', models.BigIntegerField(verbose_name='Tannarx')),
                ('sale_price', models.BigIntegerField(verbose_name='Sotuv narxi')),
                ('produced_at', models.DateField(verbose_name='Ishlab chiqarilgan sana')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('received_at', models.DateTimeField(verbose_name='Qabul qilingan sana')),
            ],
            options={
                'verbose_name': 'Partiya',
                'verbose_name_plural': 'Partiyalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Shtrix-kod')),
                ('unit', models.CharField(choices=[('piece', 'Dona'), ('kg', 'Kilogram'), ('liter', 'Litr')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('markup_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ustama foizi')),
                ('min_stock', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Minimal qoldiq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('cost_total', models.BigIntegerField(verbose_name='Umumiy tannarx')),
                ('reason', models.CharField(choices=[('expired', "Muddati o'tgan"), ('damaged', 'Shikastlangan'), ('lost', "Yo'qolgan"), ('other', 'Boshqa')], max_length=10, verbose_name='Sababi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Hisobdan chiqarish',
                'verbose_name_plural': 'Hisobdan chiqarishlar',
            },
        ),
    ]
