# Generated by Django 6.1.1 on 2026-09-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name="Kim tomonidan qo'shildi"),
        ),
        migrations.AddField(
            model_name='batch',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='catalog.batch', verbose_name='Partiya'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan hisobdan chiqarildi'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'received_at'], name='catalog_bat_product_20527f_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_remaining__gte', 0)), name='batch_qty_remaining_gte_0'),
        ),
    ]
