# Generated by Django 6.1.1 on 2026-09-17 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='produced_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarilgan sana'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qabul qilingan sana'),
        ),
    ]
