# Generated by Django 6.1.1 on 2026-09-18 03:24

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='cost_price',
            field=models.PositiveBigIntegerField(verbose_name='Tannarx'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_initial',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name="Boshlang'ich miqdor"),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sale_price',
            field=models.PositiveBigIntegerField(verbose_name='Sotuv narxi'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='cost_total',
            field=models.PositiveBigIntegerField(verbose_name='Umumiy tannarx'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Miqdor'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_initial__gt', 0)), name='batch_qty_initial_gt_0'),
        ),
    ]
